# - name: Update all packages
#   yum:
#     name: '*'
#     state: latest
#     enablerepo: "*"

# - name: Install curl and git
#   yum:
#     name: 
#       - curl
#       - git
#     state: present

# - name: Install yum-utils
#   yum:
#     name: yum-utils
#     state: present

# - name: Add Docker CE repository
#   command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

# - name: Install Docker packages
#   yum:
#     name:
#       - docker-ce
#       - docker-ce-cli
#       - containerd.io
#       - docker-buildx-plugin
#       - docker-compose-plugin
#     state: present
#     enablerepo:
#       - docker-ce-stable
#       - rhel-8-appstream-rhui-rpms
#       - rhel-8-baseos-rhui-rpms

# - name: Download and run GitLab Runner install script
#   command: curl -L -o gitlab-runner_amd64.rpm   https://packages.gitlab.com/runner/gitlab-runner/packages/fedora/32/gitlab-runner-17.1.0-1.x86_64.rpm/download.rpm

# - name: Install gitlab-runner RPM
#   command: rpm -ivh gitlab-runner_amd64.rpm

# - name: Enable Docker service
#   systemd:
#     name: docker
#     enabled: yes

# - name: Start Docker service
#   systemd:
#     name: docker
#     state: started

# - name: Add ec2-user to the Docker group
#   user:
#     name: ec2-user
#     groups: docker
#     append: yes

# - name: Start GitLab Runner
#   command: gitlab-runner start

- name: Enable GitLab Runner service
  systemd:
    name: gitlab-runner
    state: restarted

- name: copy gitlab adress
  copy:
    src: "../../ip_address.txt"
    dest: "/tmp/"

- name: Read GitLab IP from file
  slurp:
    src: "/tmp/ip_address.txt"
  register: gitlab_ip_content

- name: Set GitLab IP
  set_fact:
    gitlab_url: "{{ gitlab_ip_content.content | b64decode | trim }}"

- name: Afficher l'adresse IP
  debug:
    msg: "L'adresse IP est {{ gitlab_url }}"

- name: Ask for GitLab API token
  pause:
    prompt: "Please enter your GitLab API token"
  register: gitlab_api_token_input

- name: Register the GitLab Runner
  command: >
    gitlab-runner register --non-interactive
    --url "http://{{ gitlab_url }}:7000"
    --token "{{ gitlab_api_token_input }}"
    --description "{{ gitlab_runner_description }}"
    --executor docker \
    --docker-image "alpine:latest" \
    --docker-privileged

- name: Enable GitLab Runner service
  systemd:
    name: gitlab-runner
    enabled: yes

- name: Enable GitLab Runner service
  systemd:
    name: gitlab-runner
    state: restarted
