---
# tasks file for kube_master_setup

- name: Update all packages
  yum:
    name: '*'
    state: latest
- name: install containerd
  command: yum install https://kojipkgs.fedoraproject.org//vol/fedora_koji_archive06/packages/containerd/1.5.3/1.fc34/x86_64/containerd-1.5.3-1.fc34.x86_64.rpm
  
- name: Add Docker CE repository
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker packages
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    enablerepo:
      - docker-ce-stable
      - rhel-8-appstream-rhui-rpms
      - rhel-8-baseos-rhui-rpms

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0 

- name: Add Kubernetes repository
  copy:
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install Kubernetes components
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes

- name: Start Docker service
  systemd:
    name: docker
    state: started

- name: Initialize Kubernetes cluster on master
  command: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }}

- name: Set up kubeconfig for user on master
  command: "{{ item }}"
  args:
    creates: "{{ item.split(' ')[2].split('=')[1] }}"
  with_items:
    - mkdir -p $HOME/.kube
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config

- name: Install calico pod network
  become: false
  command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml
  
- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: true